version: '3'

services:
  flask-app:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - clickhouse

  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - /var/lib/clickhouse
